### ISSUE TITLE
Incorporate Design Storm Ponds

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/SC-RunoffModelingServices#55]
Replicate functionality for the design storm pond worksheets from the  [Spreadsheet for the SC Synthetic UH Method](https://doimspp.sharepoint.com/:x:/r/sites/SSPhaseII/Shared%20Documents/General/Planning/SC%20UH%20Method/SCDOT%20Spreadsheet_SC%20Synthetic%20UH%20Method_10%20June%202020.xlsm?d=w7adcdcb668f44f4e84347880f80b7844&csf=1&web=1&e=7pNbgk).

**Comment by amedenblik** [comment]
Pause on this until we get clarification on project requirements

**Comment by harper-wavra** [comment]
Notes: https://doimspp.sharepoint.com/sites/SSPhaseII/_layouts/OneNote.aspx?id=%2Fsites%2FSSPhaseII%2FShared%20Documents%2FGeneral%2FPlanning%2FSCSS%202%20Meeting%20Notes&wd=target%28WIM.one%7C7B131884-A0D0-489E-BEAD-8D7709995C15%2FStorm%20Pond%20Notes%7C90D99FC5-BE12-4B37-BE4B-EAE978877EEC%2F%29
