### ISSUE TITLE
Compare existing services to updated SC Synthetic Unit Hydrograph spreadsheet

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/SC-RunoffModelingServices#56]
The existing services relevant to the SC Synthetic Unit Hydrograph were developed with an [old version of the spreadsheet](https://doimspp.sharepoint.com/:x:/r/sites/SSPhaseII/Shared%20Documents/General/Planning/SC%20UH%20Method/SCDOT%20Spreadsheet_SC%20Synthetic%20UH%20Method_10%20June%202020.xlsm?d=w7adcdcb668f44f4e84347880f80b7844&csf=1&web=1&e=VV1aFe).

We need to compare services and results to the [new version of the spreadsheet](https://doimspp.sharepoint.com/:x:/r/sites/SSPhaseII/Shared%20Documents/General/Planning/SC%20UH%20Method/SCDOT%20Spreadsheet_SC%20Synthetic%20UH_Verified%20on%205%20August%202022.xlsm?d=w9840a86621414c59884b8aa9e0ad817c&csf=1&web=1&e=qFvYBb).

**Comment by amedenblik** [comment]
A new spreadsheet has been created: https://doimspp-my.sharepoint.com/:x:/g/personal/kkolb_usgs_gov/EetuQRkt-xtDjq-fHdhZd6wBCQaSyjGpVRadVBDnP8PHog?CID=b202ac48-fd6d-b4d6-cec4-dff77e1cc5bd

**Comment by harper-wavra** [comment]
- [x] **weightedcurvenumber - how to choose which return period (in runoff weighted CN calculator) to get numbers from? Is that a variable we need? Our services are returning the 10 yr period and the excel sheet is returning the 25.** 
- [x] prf
- [x] rainfall
- [x] rainfalldistributioncurve
- [x] RI2
- [x] ~~ruralhydrographbohman1989~~ - not in spreadsheet
- [x] ~~ruralhydrographbohman1992~~ - not in spreadsheet
- [x] lagtimetc
- [ ] **traveltimetc - sheet flow seems off - equations for travel time in sheet flow have been changed from the old version. The rest looked good.**
- [x] scsystheticunithydrograph
- [x] calculatemissingparametersSCUH

**Comment by harper-wavra** [comment]
Made issues for the two changes I found. Going to email SC about the changes and make sure we didnt miss any.

**Comment by harper-wavra** [comment]
I think this can be closed - issues have been made for all the changes found. Please reopen the issue if you think we need to look into this further.
