### ISSUE TITLE
Rainfall endpoint failing 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/SC-RunoffModelingServices#84]
When I test the rainfall endpoint at https://streamstats.usgs.gov/local/scrunoffservices/docs#/, it is failing.

**Comment by amedenblik** [comment]
I think `https://hdsc.nws.noaa.gov/cgi-bin/new/cgi_readH5.py?` should be replaced with `https://hdsc.nws.noaa.gov/cgi-bin/hdsc/new/cgi_readH5.py?`
