### ISSUE TITLE
weightedcurvenumber add AEP

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/SC-RunoffModelingServices#86]
In the weightedcurvenumber endpoint there should be an option to select AEP. You want to use the CN, S and Ia from that selected AEP.

It is currently just taking the 10% values. 

See the Area Weighted/Runoff CN calculator sheets along with the WS & UH Data & Runoff Results sheet.

**Comment by amedenblik** [comment]
Related to #56

**Comment by amedenblik** [comment]
I reviewed the spreadsheets and the existing code. The code is working correctly as-is. The `weightedCurveNumber` function intakes value P24hr, which is the "24-hour Rainfall Depth (P), in inches; comes from rainfallData function for **corresponding AEP**". So the AEP is being accounted for already. 

I remember now that I had discovered the error (where it was just taking the 10% values) in the [first spreadsheet](https://doimspp.sharepoint.com/:x:/r/sites/SSPhaseII/Shared%20Documents/General/Planning/SC%20UH%20Method/SCDOT%20Spreadsheet_SC%20Synthetic%20UH%20Method_10%20June%202020.xlsm?d=w7adcdcb668f44f4e84347880f80b7844&csf=1&web=1&e=VV1aFe), and reported it to Tom/DOP. That's when they shared the [second spreadsheet](https://doimspp.sharepoint.com/:x:/r/sites/SSPhaseII/Shared%20Documents/General/Planning/SC%20UH%20Method/SCDOT%20Spreadsheet_SC%20Synthetic%20UH_Verified%20on%205%20August%202022.xlsm?d=w9840a86621414c59884b8aa9e0ad817c&csf=1&web=1&e=qFvYBb), which fixed the error. The [third spreadsheet](https://doimspp-my.sharepoint.com/:x:/g/personal/kkolb_usgs_gov/EetuQRkt-xtDjq-fHdhZd6wBCQaSyjGpVRadVBDnP8PHog?CID=b202ac48-fd6d-b4d6-cec4-dff77e1cc5bd) also has the error fixed.

Case closed, I think! Please reopen the issue if you think we need to look into this further.
