### ISSUE TITLE
traveltimetc change 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/SC-RunoffModelingServices#87]
traveltimetc - sheet flow equations changed from old version

changed to 
=(0.42/SQRT(H19))*(H17*H16/SQRT(H18/100))^0.8
from 
=(0.42/SQRT(H19))*(H17*H16/SQRT((MAX(0.0001,H18)/100))^0.8)

**Comment by amedenblik** [comment]
Related to #56

**Comment by harper-wavra** [comment]
- [ ] surface["Overland Slope"] must be > 0 or user will receive an error
- [ ] edit the example request to not be 0 - change it to match the spreadsheet
